---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - javascript
        - python
  scss-lint:
    enabled: true
  eslint:
    enabled: true
  fixme:
    enabled: true
  radon:
    enabled: true

ratings:
  paths:
    - "**.css"
    - "**.inc"
    - "**.js"
    - "**.ts"
    - "**.module"
    - "**.php"
    - "**.py"
    - "**.rb"

exclude_paths:
  - "src/server/deprecated/cheeses/output/"
  - "typings/"
  - "**.pdf"
