language: node_js
jdk:
  - oraclejdk8
env:
  - NODE_ENV=production
  - NODE_ENV=staging
node_js:
  - "14.4.0"
install:
  - npm install
before_script: 
  - npm test
addons:
    code_climate:
        repo_token: f4fed7e049fce0a5cfd0bedb8ad6802c1e027cf596c6317ba6aaae9b534df611
