cacheFolder: ./.yarn/cache

defaultLanguageName: node

enableGlobalCache: false

logFilters:
  - code: YN0013
    level: discard
  - pattern: "*provides @yarnpkg/*"
    level: discard
  - pattern: "querystring@npm* is deprecated*"
    level: discard
  - pattern: "fsevents@npm* Implicit dependencies on node-gyp*"
    level: discard
  - pattern: "evp_bytestokey@npm* Implicit dependencies on node-gyp*"
    level: discard
  - pattern: "@npmcli/move-file* is deprecated*"
    level: discard

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.2.4.cjs
