#
# Homepage: Yarn Configuration
#

nodeLinker: pnp
yarnPath: .yarn/releases/yarn-4.1.1.cjs
cacheFolder: ./.yarn/cache
enableGlobalCache: false
logFilters:
  - code: YN0013
    level: discard
  - level: discard
    pattern: "*provides @yarnpkg/*"
  - level: discard
    pattern: querystring@npm* is deprecated*
  - level: discard
    pattern: fsevents@npm* Implicit dependencies on node-gyp*
  - level: discard
    pattern: evp_bytestokey@npm* Implicit dependencies on node-gyp*
  - level: discard
    pattern: "@npmcli/move-file* is deprecated*"
