plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

logFilters:
  # Ignore "can't be found in the cache and will be fetched from the remote registry"
  - code: YN0013
    level: discard

yarnPath: .yarn/releases/yarn-3.0.1-rc.2.cjs
enableGlobalCache: false
defaultLanguageName: "node"
cacheFolder: "./.yarn/cache"
