# Fix line endings on Windows
init:
  - git config --global core.autocrlf true
# What combinations to test
environment:
  matrix:
    - nodejs_version: "4"
    - nodejs_version: "5"
platform:
  - x86
  - x64
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g npm@">=3.9.6"
  - npm install -g grunt-cli
  - npm install
  - grunt
test_script:
  - node --version && npm --version
build: off
matrix:
  fast_finish: true
cache:
  - node_modules -> package.json