init:
  # Fix line endings on Windows
  - git config --global core.autocrlf true
environment:
  matrix:
    - nodejs_version: "8.9.4"
    - nodejs_version: "10.12.0"
    - nodejs_version: "12.18.1"
platform:
  - x86
  - x64
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
test_script:
  - npm test
  - node --version
  - npm --version
build: off
matrix:
  fast_finish: true
cache:
  - node_modules -> package.json
