
trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

jobs:

- job: ubuntu_critical

  steps:

    - task: NodeTool@0
      inputs:
        versionSpec: '8.x'
      displayName: 'Install Node.js'

    - script: |
        npm install -g npm@">=5.6.0"
        npm install -g grunt-cli
        npm install -g bower-cli
        npm install --force
        npm update
      displayName: 'Install Dependencies'

    - script: |
        bower install
      displayName: 'Bower'

    - script: |
        grunt
        grunt dist
      displayName: 'Grunt'
