
trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g npm@">=5.6.0"
    npm install -g grunt-cli
    npm install --force
    npm update
    grunt
    grunt dist
  displayName: 'npm install and run grunt'