#
# Joel Van Eenwyk homepage configuration
#
# cspell:ignore changeFreq, pasdmwalpk, noFollow, noOpener, fontAwesome, mhchem, SVZQ, noReffer
baseURL = "https://www.joelvaneenwyk.com/"
languageCode = "en-us"
title = "Joel Van Eenwyk"
theme = "base"
publishDir = "dist/www"
enableEmoji = true
defaultContentLanguage = "en"
enableRobotsTXT = true
enableGitInfo = true
# Enable KaTeX (https://katex.org/) globally
math = true

# Author config
[author]
name = "Joel Van Eenwyk"
email = "joel.vaneenwyk@gmail.com"
link = ""

[build]
useResourceCacheWhen = 'never'

[permalinks]
"/" = "/:filename"

# Sitemap config
# 网站地图配置
[sitemap]
changefreq = "weekly"
filename = "sitemap.xml"
priority = 0.5

# Permalinks config (https://gohugo.io/content-management/urls/#permalinks)
[Permalinks]
# posts = ":year/:month/:filename"
posts = ":filename"

# Privacy config (https://gohugo.io/about/hugo-and-gdpr/)
[privacy]

# ...
[privacy.twitter]
enableDNT = true

[privacy.youtube]
privacyEnhanced = true

# Options to make output .md files
[mediaTypes]

[mediaTypes."text/plain"]
suffixes = ["md"]

# Options to make output .md files=
[outputFormats.MarkDown]
mediaType = "text/plain"
isPlainText = true
isHTML = false

# Options to make hugo output files
[outputs]
home = ["HTML", "RSS", "JSON"]
page = ["HTML", "MarkDown"]
section = ["HTML", "RSS"]
taxonomy = ["HTML", "RSS"]

[taxonomies]
series = "series"
tag = "tags"
category = "categories"

[languages]

[languages.en]
weight = 1
# language code
languageCode = "en"
# language name
languageName = "English"
# whether to include Chinese/Japanese/Korean
hasCJKLanguage = false
# default amount of posts in each pages
paginate = 12
# copyright description used only for seo schema
copyright = "This work is licensed under an MIT License."

# Menu config
[languages.en.menu]

[[languages.en.menu.main]]
identifier = "posts"
# you can add extra information before the name (HTML format is supported), such as icons
pre = ""
# you can add extra information after the name (HTML format is supported), such as icons
post = ""
name = "Posts"
url = "/posts/"
# title will be shown when you hover on this menu link.
title = ""
weight = 1

[[languages.en.menu.main]]
identifier = "tags"
pre = ""
post = ""
name = "Tags"
url = "/tags/"
title = ""
weight = 2

[[languages.en.menu.main]]
identifier = "categories"
pre = ""
post = ""
name = "Categories"
url = "/categories/"
title = ""
weight = 3

[[languages.en.menu.main]]
identifier = "documentation"
pre = ""
post = ""
name = "Docs"
url = "/categories/documentation/"
title = ""
weight = 4

[[languages.en.menu.main]]
identifier = "about"
pre = ""
post = ""
name = "About"
url = "/about/"
title = ""
weight = 5

[[languages.en.menu.main]]
identifier = "github"
pre = "<i class='fab fa-github fa-fw'></i>"
post = ""
name = ""
url = "https://github.com/joelvaneenwyk/homepage"
title = "GitHub"
weight = 6

[languages.en.params]
# site description
description = "About Joel Van Eenwyk"
# site keywords
keywords = [
  "programmer",
  "jvaneenwyk",
  "van eenwyk",
  "joel van eenwyk",
  "bingo",
  "vfx journal",
  "vfx",
  "houdini",
  "haskell"
]

# App icon config
[languages.en.params.app]
# optional site title override for the app when added to an iOS home screen or Android launcher
title = "Joel Van Eenwyk"
# whether to omit favicon resource links
noFavicon = false
# modern SVG favicon to use in place of older style .png and .ico files
svgFavicon = "/favicon.svg"
# Android browser theme color
themeColor = "#ffffff"
# Safari mask icon color
iconColor = "#5bbad5"
# Windows v8-10 tile color
tileColor = "#da532c"

# Search config
[languages.en.params.search]
enable = true
# type of search engine ("lunr", "algolia")
type = "algolia"
# max index length of the chunked content
contentLength = 4000
# placeholder of the search bar
placeholder = ""
# max number of results length
maxResultLength = 10
# snippet length of the result
snippetLength = 30
# HTML tag name of the highlight part in results
highlightTag = "em"
# whether to use the absolute URL based on the baseURL in search index
absoluteURL = false

[languages.en.params.search.algolia]
index = "index.en"
appID = "PASDMWALPK"
searchKey = "b42948e51daaa93df92381c8e2ac0f93"

# Home page config
[languages.en.params.home]
# amount of RSS pages
rss = 10

# Home page profile
[languages.en.params.home.profile]
enable = true
# Gravatar Email for preferred avatar in home page
gravatarEmail = ""
# URL of avatar shown in home page
avatarURL = "/images/avatar.jpg"
# title shown in home page (HTML format is supported)
title = ""
# subtitle shown in home page
subtitle = "Programmer, explorer, and life enthusiast. Work for Microsoft and previously worked in games and part of Havok middleware team. Views expressed here are my own."
# whether to use typeit animation for subtitle
typeit = false
# whether to show social links
social = true
# disclaimer (HTML format is supported)
disclaimer = ""

# Home page posts
[languages.en.params.home.posts]
enable = true
# special amount of posts in each home posts page
paginate = 6

# Social config in home page
[languages.en.params.social]
GitHub = "joelvaneenwyk"
Linkedin = "joelvaneenwyk"
Twitter = "joelvaneenwyk"
Instagram = "jvaneenwyk"
Email = "joel.vaneenwyk@gmail.com"
MobyGames = "developer/sheet/view/developerId,231132"
RSS = true

[params]
author = "Joel Van Eenwyk"
description = "A simple monospaced resume theme for Hugo."
favicon = "images/favicon.ico" # path to a .ico to use as favicon
# LoveIt theme version
version = "0.2.X"
# site default theme ("light", "dark", "auto")
defaultTheme = "auto"
# public git repo url only then enableGitInfo is true
gitRepo = "https://github.com/joelvaneenwyk/homepage"
# which hash function used for SRI, when empty, no SRI is used ("sha256", "sha384", "sha512", "md5")
fingerprint = "sha512"
# date format
dateFormat = "2006-01-02"
# website images for Open Graph and Twitter Cards
images = ["/logo.png"]

# Header config
[params.header]
# desktop header mode ("fixed", "normal", "auto")
desktopMode = "fixed"
# mobile header mode ("fixed", "normal", "auto")
mobileMode = "auto"

# Header title config
[params.header.title]
# URL of the LOGO
logo = "/images/jve_stamp_bright_red.png"
# title name
name = "  Joel Van Eenwyk"
# you can add extra information before the name (HTML format is supported), such as icons
pre = "" # "<i class='fas fa-laptop-code'></i>"
# you can add extra information after the name (HTML format is supported), such as icons
post = ""
# whether to use typeit animation for title name
typeit = false

# Footer config
[params.footer]
enable = true
# Custom content (HTML format is supported)
custom = ''
# whether to show Hugo and theme info
hugo = true
# whether to show copyright info
copyright = true
# whether to show the author
author = true
# site creation time
since = 2021
# license info (HTML format is supported)
license = '<a rel="license external nofollow noopener noreffer" href="https://opensource.org/licenses/MIT/" target="_blank">MIT License</a>'

# Section (all posts) page config
[params.section]
# special amount of posts in each section page
paginate = 10
# date format (month and day)
dateFormat = "01-02"
# amount of RSS pages
rss = 10

# List (category or tag) page config
[params.list]
# special amount of posts in each list page
paginate = 20
# date format (month and day)
dateFormat = "01-02"
# amount of RSS pages
rss = 10

# Page config
[params.page]
hiddenFromHomePage = false
hiddenFromSearch = false
twemoji = false
lightgallery = false
ruby = true
fraction = true
fontawesome = true
linkToMarkdown = true
rssFullText = false

# Table of the contents config
[params.page.toc]
enable = true
# whether to keep the static table of the contents in front of the post
keepStatic = false
# whether to make the table of the contents in the sidebar automatically collapsed
auto = true

# Code config
[params.page.code]
# whether to show the copy button of the code block
copy = true
# the maximum number of lines of displayed code by default
maxShownLines = 20

# KaTeX mathematical formulas config (KaTeX https://katex.org/)
[params.page.math]
enable = false
# default block delimiter is $$ ... $$ and \\[ ... \\]
blockLeftDelimiter = ""
blockRightDelimiter = ""
# default inline delimiter is $ ... $ and \\( ... \\)
inlineLeftDelimiter = ""
inlineRightDelimiter = ""
# KaTeX extension copy_tex
copyTex = true
# KaTeX extension mhchem
mhchem = true

# Mapbox GL JS config (Mapbox GL JS https://docs.mapbox.com/mapbox-gl-js)
[params.page.mapbox]
# access token of Mapbox GL JS
accessToken = "pk.eyJ1IjoiZGlsbG9uenEiLCJhIjoiY2s2czd2M2x3MDA0NjNmcGxmcjVrZmc2cyJ9.aSjv2BNuZUfARvxRYjSVZQ"
# style for the light theme
lightStyle = "mapbox://styles/mapbox/light-v10?optimize=true"
# style for the dark theme
darkStyle = "mapbox://styles/mapbox/dark-v10?optimize=true"
# whether to add NavigationControl (https://docs.mapbox.com/mapbox-gl-js/api/#navigationcontrol)
navigation = true
# whether to add GeolocateControl (https://docs.mapbox.com/mapbox-gl-js/api/#geolocatecontrol)
geolocate = true
# whether to add ScaleControl (https://docs.mapbox.com/mapbox-gl-js/api/#scalecontrol)
scale = true
# whether to add FullscreenControl (https://docs.mapbox.com/mapbox-gl-js/api/#fullscreencontrol)
fullscreen = true

# Social share links in post page
[params.page.share]
enable = true
Twitter = true
Reddit = true

# Comment config
[params.page.comment]
enable = true

# Disqus comment config (https://disqus.com/)
[params.page.comment.disqus]
enable = true
# Disqus shortname to use Disqus in posts
shortname = "joelvaneenwyk"

# Gitalk comment config (https://github.com/gitalk/gitalk)
[params.page.comment.gitalk]
enable = false
owner = ""
repo = ""
clientId = ""
clientSecret = ""

# Third-party library config
[params.page.library]

[params.page.library.css]

# someCSS = "some.css"
# located in "assets/"
# or some CSS = "https://cdn.example.com/some.css"
[params.page.library.js]

# someJavascript = "some.js"
# located in "assets/"
# or some Javascript = "https://cdn.example.com/some.js"
# Page SEO config
[params.page.seo]
# image URL
images = []

# Publisher info
[params.page.seo.publisher]
name = "Joel Van Eenwyk"
logoUrl = "/images/avatar.png"

# TypeIt config
[params.typeit]
# typing speed between each step (measured in milliseconds)
speed = 100
# blinking speed of the cursor (measured in milliseconds)
cursorSpeed = 1000
# character used for the cursor (HTML format is supported)
cursorChar = "|"
# cursor duration after typing finishing (measured in milliseconds, "-1" means unlimited)
duration = -1

# Site verification code for Google/Bing/Yandex/Pinterest/Baidu
[params.verification]
google = ""
bing = ""
yandex = ""
pinterest = ""
baidu = ""

# Site SEO config
[params.seo]
# image URL
image = ""
# thumbnail URL
thumbnailUrl = ""

# Analytics config
[params.analytics]
enable = true

# Google Analytics
[params.analytics.google]
enable = true
id = "UA-63489189-1"
# whether to anonymize IP
anonymizeIP = true

# Cookie consent config
[params.cookieconsent]
enable = false

# text strings used for Cookie consent banner
[params.cookieconsent.content]
message = ""
dismiss = ""
link = ""

# CDN config for third-party library files
[params.cdn]
# CDN data file name, disabled by default
# ("jsdelivr.yml")
# located in "themes/LoveIt/assets/data/cdn/" directory
# you can store your own data files in the same path under your project:
# "assets/data/cdn/"
data = "jsdelivr.yml"

# Compatibility config
[params.compatibility]
# whether to use Polyfill.io to be compatible with older browsers
polyfill = true
# whether to use object-fit-images to be compatible with older browsers
objectFit = false

# Markup related configuration in Hugo
[markup]

# Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
[markup.highlight]
codeFences = true
guessSyntax = true
lineNos = true
lineNumbersInTable = true
# false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
noClasses = false

# Goldmark is from Hugo 0.60 the default library used for Markdown
[markup.goldmark]

[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = true

[markup.goldmark.renderer]
# whether to use HTML tags directly in the document
unsafe = true

# Table Of Contents settings
[markup.tableOfContents]
startLevel = 2
endLevel = 6
