version: '3.8'

volumes:
  mnt_yarn_cache:
  mnt_yarn_unplugged:
  mnt_dist:
  mnt_git:

services:
  homepage:
    image: homepage
    container_name: homepage_base
    build:
      context: .
      dockerfile: ./src/docker/Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000

  server:
    image: heroku/heroku:20
    container_name: homepage_heroku
    volumes:
      - .:/app/
      - ./dist/tmp/git/:/app/.git/
      - mnt_yarn_cache:/app/.yarn/cache/
      - mnt_yarn_unplugged:/app/.yarn/unplugged/
      - mnt_dist:/app/dist/
    stdin_open: true
    tty: true
