# yaml-language-server: $schema=https://taskfile.dev/schema.json
# https://taskfile.dev
# cspell:ignore taskfile,vcpkg,msbuild,makefiles,deinit

version: '3'

vars:
  HUGO_WINDOWS: 'scoop/shims/hugo.exe'
  HOME: '{{if eq OS "windows"}}{{ env "USERPROFILE" }}{{else}}{{ env "HOME" }}{{end}}'

env:
  HOME: '{{.HOME | default "./.build/home"}}'

tasks:
  default:
    cmds:
      - task: build

  act:
    vars:
      DOCKER_IMAGE_URL: ghcr.io/jefuller/artifact-server:latest
      DOCKER_CONTAINER_NAME: artifact-server
      AUTH_KEY: homepage-artifact-key
    cmds:
      # https://github.com/nektos/act/issues/329#issuecomment-1905955589
      - cmd: | # shell
          docker pull "{{.DOCKER_IMAGE_URL}}"
      - cmd: | # shell
          docker run \
            -d --name "{{.DOCKER_CONTAINER_NAME}}" \
            -p 8080:8080 \
            --add-host host.docker.internal:host-gateway \
            -e AUTH_KEY="{{.AUTH_KEY}}" \
            "{{.DOCKER_IMAGE_URL}}"
      - defer: | # shell
          docker rm -f "{{.DOCKER_CONTAINER_NAME}}"
      - cmd: | # shell
          if [ ! -e $HOME/.actrc ] || [ ! grep $HOME/.actrc "artifact-server-path" ]; then
            mkdir -p "$HOME/.act/"
            echo "--artifact-server-path $HOME/.act" >> $HOME/.actrc
          fi
      - cmd: | # shell
          echo "Starting act with artifact server..."
          gh act \
            --env ACTIONS_RUNTIME_URL=http://host.docker.internal:8080/ \
            --env ACTIONS_RUNTIME_TOKEN="{{.AUTH_KEY}}" \
            --env ACTIONS_CACHE_URL=http://host.docker.internal:8080/ \
            --artifact-server-path $HOME/.act

  install-hugo:
    cmds:
      - cmd: scoop install "hugo-extended"
        platforms: [windows]
      - cmd: go install -tags extended github.com/gohugoio/hugo@latest
        platforms: [darwin, linux]

  setup:
    deps: [install-hugo]
    vars:
      PROTO_WINDOWS: '.proto/bin/proto.exe'
    cmds:
      - cmd: |
          cmd.exe /d /c call "{{joinPath .HOME (.PROTO_WINDOWS | default "")}}" uninstall --yes yarn
        platforms: [windows]
        silent: true
        ignore_error: true
      - cmd: yarn config set --home enableTelemetry false

  build:
    deps: [setup]
    cmds:
      - yarn install
      - yarn build

  hugo:
    deps: [setup]
    vars:
      HUGO: '{{if eq OS "windows"}}hugo{{else}}hugo{{end}}'
    cmds:
      - cmd: |
          {{.HUGO}} --forceSyncStatic --buildDrafts --buildExpired --buildFuture --cleanDestinationDir --gc --enableGitInfo
