init:
  # Fix line endings on Windows
  - git config --global core.autocrlf true
environment:
  matrix:
    - nodejs_version: "14"
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
test_script:
  - npm test
  - npm --version
  - node --version
build: off
matrix:
  fast_finish: true
cache:
  - node_modules -> package.json
