
trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

jobs:

- job: ubuntu_critical

  steps:

    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
      displayName: 'Install Dependencies'

    - script: |
        grunt
        grunt dist
      displayName: 'Grunt'
