name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write
  checks: write
  deployments: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        node:
          - 18
          - 20
          - 21
        platform:
          - ubuntu-latest
          # - macos-latest
          # - windows-latest

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4
        with:
          # Fetch Hugo themes (true OR recursive)
          submodules: recursive
          # Fetch all history for .GitInfo and .Lastmod
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: latest
          extended: true

      - name: Install Packages
        run: |
          yarn install

      - name: Build Hugo Site
        run: hugo --buildDrafts --buildExpired --buildFuture --cleanDestinationDir --verbose

      - name: Build Source
        run: |
          yarn build

      - uses: actions/upload-artifact@v4
        name: Upload Site Artifact
        with:
          name: website-${{ matrix.platform }}-${{ matrix.node }}
          path: '.dist/www/'

  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          # Fetch Hugo themes (true OR recursive)
          submodules: recursive
          # Fetch all history for .GitInfo and .Lastmod
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v4

      - run: corepack enable
      - run: sudo git config --system --add safe.directory /github/workspace

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Install Packages
        run: |
          yarn install

      - name: Build Hugo Site
        run: hugo --buildDrafts --buildExpired --buildFuture --cleanDestinationDir --verbose

      - name: Build Source
        run: |
          yarn build

      - name: Build And Deploy
        id: builddeploy
        uses: joelvaneenwyk/static-web-apps-deploy@v2
        with:
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_BUSH_057D1041E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: 'upload'
          app_location: './' # App source code path
          api_location: '' # Api source code path - optional
          output_location: 'dist/www/' # Built app content directory - optional

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    needs: build
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: joelvaneenwyk/static-web-apps-deploy@v2
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_BUSH_057D1041E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: 'close'
          app_location: './' # App source code path
          api_location: '' # Api source code path - optional
          output_location: 'dist/www/' # Built app content directory - optional
