name: hugo

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    strategy:
      matrix:
        node:
          - 16
          - 18
          - 20
        platform:
          - ubuntu-20.04
          - macos-11
          - windows-2019

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v3
        with:
          # Fetch Hugo themes (true OR recursive)
          submodules: recursive
          # Fetch all history for .GitInfo and .Lastmod
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install Yarn
        run: npm install -g yarn

      # We do not require Go installed but installing anyways so that we have the
      # option to either install our own version of Hugo or run plugins.
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "^1.16.7"
      - run: go version

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.85.0"
          extended: true

      - name: Install Packages
        run: |
          yarn install

      - name: Hugo Build
        run: |
          hugo
