name: hugo

on:
  push:
    branches: [ main, revamp ]
  pull_request:
    branches: [ main, revamp ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    - uses: actions/checkout@v2
      with:
        # Fetch Hugo themes (true OR recursive)
        submodules: recursive
        # Fetch all history for .GitInfo and .Lastmod
        fetch-depth: 0

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.85.0'
        # extended: true

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Yarn
      run: npm install -g yarn

    - name: Install Packages
      run: |
        yarn install

    - name: Hugo Build
      run: |
        hugo
