name: hugo

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        node:
          - 16
          - 18
        platform:
          - ubuntu-20.04
          - macos-11
          - windows-2019

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4
        with:
          # Fetch Hugo themes (true OR recursive)
          submodules: recursive
          # Fetch all history for .GitInfo and .Lastmod
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - run: corepack enable

      - run: sudo git config --system --add safe.directory /github/workspace

      # We do not require Go installed but installing anyways so that we have the
      # option to either install our own version of Hugo or run plugins.
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Install Packages
        run: |
          yarn install

      - uses: jakejarvis/hugo-build-action@master
        name: Build Hugo Site
        with:
          args: --buildDrafts --buildExpired --buildFuture --cleanDestinationDir --verbose

      - name: Build Source
        run: |
          yarn build

      - uses: actions/upload-artifact@v4
        name: Upload Site Artifact
        with:
          name: website-${{ matrix.platform }}-${{ matrix.node }}
          path: '.dist/www/'
