name: hugo

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        node:
          - 16
          - 18
        platform:
          - ubuntu-20.04
          - macos-11
          - windows-2019

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4
        with:
          # Fetch Hugo themes (true OR recursive)
          submodules: recursive
          # Fetch all history for .GitInfo and .Lastmod
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - run: corepack enable

      - run: sudo git config --system --add safe.directory /github/workspace

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Install Packages
        run: |
          yarn install

      - name: Build Hugo Site
        run: hugo --buildDrafts --buildExpired --buildFuture --cleanDestinationDir --verbose

      - name: Build Source
        run: |
          yarn build

      - uses: actions/upload-artifact@v4
        name: Upload Site Artifact
        with:
          name: website-${{ matrix.platform }}-${{ matrix.node }}
          path: '.dist/www/'
